- id: copyright
  name: Auto-add copyright header
  description: This hook auto-adds copyright header
  entry: copyright
  language: python
  types: [text]
  args: [-S, -q, -c, .copyright.config.json]
